package unifan.chat_bot_vendas.domain.enums;

public enum EstadoSessao {
    INICIAL,
    AGUARDANDO_PRODUTO,
    AGUARDANDO_RESOLUCAO_ITEM,
    AGUARDANDO_CONFIRMACAO_PRODUTO,
    AGUARDANDO_QUANTIDADE,
    AGUARDANDO_CONFIRMACAO_COMPRA,
    AGUARDANDO_CONFIRMACAO_CARRINHO,
    AGUARDANDO_FORMA_PAGAMENTO,
    AGUARDANDO_DADOS_PAGAMENTO,
    SAIR_COMPRA
}
