package unifan.chat_bot_vendas.domain.enums;

public enum TipoAcao {
    INICIAR_COMPRA,
    CHECAR_ESTOQUE,
    VERIFICAR_VENDAS,
    CONTINUAR_PEDIDO,
    ATUALIZAR_PEDIDO,
    DELETAR_PEDIDO,
    SAIR_CHAT_VENDA,
    COMPRAR_CAMISA,
    COMPRAR_CALCA,
    COMPRAR_SHORT_BERMUDA,
    COMPRAR_BLUSA,
    COMPRAR_SAPATO
}
